textury/arlocal

src/graphql/resolvers.ts

This PR fixes the two errors that occurred when running a `transaction` query. 😄

fix: correctly resolve `transaction` query

---

package.json
src/routes/transaction.ts
yarn.lock

This PR integrates @joshbenaron's new [ANS-104](https://github.com/joshbenaron/arweave-standards/blob/ans104/ans/ANS-104.md) ([package](https://github.com/joshbenaron/ans104)).
P.S. Might want to switch to a stable release and not the GitHub branch.

feat: integrate ANS-104

---

package.json
src/db/data.ts
src/db/transaction.ts
src/routes/data.ts
src/routes/transaction.ts
yarn.lock

swapped from ans104 to arbundles, fixed txAnchorRoute returning a transaction instead of a block

swapped from ans104 to arbundles, fixed txAnchorRoute returning a transaction instead of a block

---

src/db/data.ts

fixing data encoding

---

__tests__/data/example-contract-state.json
__tests__/data/example-contract.js
__tests__/smartweave.spec.ts
jest.config.js
package.json
src/app.ts
test-setup.ts
yarn.lock

added smartweave integration tests

---

package.json

Adds minimum node version requirement

feat: adds node version requirements

---

.dockerignore
Dockerfile
yarn.lock

- Use node 16 for build and node 16 alpine for prod.
- Added dumb-init.
- Set node as the user for docker.
- Exposed the default port (1984).
- Updated dockerignore

updated docker

---

package.json
src/routes/transaction.ts

fix: create chunks for tx without chunks created from client

---

src/routes/transaction.ts

fix: fix findOne of undefined

---

package.json
src/app.ts
src/routes/transaction.ts
yarn.lock

chore: add /tx/:id/data.json endpoint to get parsed manifest data

---

src/db/transaction.ts

Insert empty string for transaction.last_tx if undefined on transaction
fix for #75

Insert empty string for transaction.last_tx if undefined

---

__tests__/transaction.spec.ts
src/db/initialize.ts
src/db/transaction.ts
src/faces/transaction.ts
src/middlewares/transaction.ts
src/routes/transaction.ts

fix: restrict only data items on /tx/* endpoints

---

src/db/chunks.ts
src/routes/transaction.ts

fix(same-txs-data): move non-chunk tx chunks creation to post /tx endpoint

---

src/routes/chunk.ts

changed offset handler

---

src/db/wallet.ts
src/routes/transaction.ts

fix: fix once in a while 204 no content response on /wallet/{address}/balance endpoint

---

src/app.ts

chore: add wild card origin header and resource policy header to cross origin

---

src/app.ts

fix: fix not found error after setting cors header

---

src/db/wallet.ts

fix: fix null on walletDB.addWallet

---

src/app.ts
src/db/block.ts

bug reference - https://discord.com/channels/854335438508523520/854543359275827200/971346022724939837

fix: save genesis block

---

src/routes/blocks.ts

fix: return block timestamp in seconds

---

package.json
yarn.lock

:bug: fix(deps): bump arbundles from 0.6.12 to 0.6.19

---

src/routes/data.ts

:sparkles: feat: add seek support to served audios via content-range header

---

src/middlewares/transaction.ts

- validate required fields using undefined checks since `!("") == true`.
- convert base64url to buffer the right way on `body.owner` compared to `target` field.

:bug: fix: fix minor issues on POST /tx endpoint validation

---

src/app.ts

:bug: fix: increase json body limit from default 1mb

---

src/routes/transaction.ts

Closes #119 
Check bundle tx data_size against last chunk offset - first chunk offset + last chunk length

Handle chunk uploaded binary bundle un-bundling

---

src/routes/transaction.ts

Skip chunk creation for bundled data-item transactions

---

src/app.ts
src/routes/transaction.ts

:bug: fix: fix inconsistent pricing between GET /price and POST /tx

---

src/app.ts
src/graphql/resolvers.ts
src/graphql/server.ts

:bug: fix: use current network height as gql maxHeight

---

src/app.ts

ARCONNECT developers have hopefully solved this issue by now.

feature: allow HEAD requests again
